// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: shared/proto/province.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvinceService_GetProvinceByIdHdl_FullMethodName = "/province.ProvinceService/GetProvinceByIdHdl"
)

// ProvinceServiceClient is the client API for ProvinceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvinceServiceClient interface {
	GetProvinceByIdHdl(ctx context.Context, in *GetProvinceByIdRequest, opts ...grpc.CallOption) (*ProvinceResponse, error)
}

type provinceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvinceServiceClient(cc grpc.ClientConnInterface) ProvinceServiceClient {
	return &provinceServiceClient{cc}
}

func (c *provinceServiceClient) GetProvinceByIdHdl(ctx context.Context, in *GetProvinceByIdRequest, opts ...grpc.CallOption) (*ProvinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvinceResponse)
	err := c.cc.Invoke(ctx, ProvinceService_GetProvinceByIdHdl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvinceServiceServer is the server API for ProvinceService service.
// All implementations should embed UnimplementedProvinceServiceServer
// for forward compatibility.
type ProvinceServiceServer interface {
	GetProvinceByIdHdl(context.Context, *GetProvinceByIdRequest) (*ProvinceResponse, error)
}

// UnimplementedProvinceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvinceServiceServer struct{}

func (UnimplementedProvinceServiceServer) GetProvinceByIdHdl(context.Context, *GetProvinceByIdRequest) (*ProvinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinceByIdHdl not implemented")
}
func (UnimplementedProvinceServiceServer) testEmbeddedByValue() {}

// UnsafeProvinceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvinceServiceServer will
// result in compilation errors.
type UnsafeProvinceServiceServer interface {
	mustEmbedUnimplementedProvinceServiceServer()
}

func RegisterProvinceServiceServer(s grpc.ServiceRegistrar, srv ProvinceServiceServer) {
	// If the following call pancis, it indicates UnimplementedProvinceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvinceService_ServiceDesc, srv)
}

func _ProvinceService_GetProvinceByIdHdl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvinceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvinceServiceServer).GetProvinceByIdHdl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvinceService_GetProvinceByIdHdl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvinceServiceServer).GetProvinceByIdHdl(ctx, req.(*GetProvinceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvinceService_ServiceDesc is the grpc.ServiceDesc for ProvinceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvinceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "province.ProvinceService",
	HandlerType: (*ProvinceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProvinceByIdHdl",
			Handler:    _ProvinceService_GetProvinceByIdHdl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/province.proto",
}
