// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: shared/proto/ward.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWardByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWardByIdRequest) Reset() {
	*x = GetWardByIdRequest{}
	mi := &file_shared_proto_ward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWardByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardByIdRequest) ProtoMessage() {}

func (x *GetWardByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_ward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardByIdRequest.ProtoReflect.Descriptor instead.
func (*GetWardByIdRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_ward_proto_rawDescGZIP(), []int{0}
}

func (x *GetWardByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ProvinceId    int32                  `protobuf:"varint,4,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WardResponse) Reset() {
	*x = WardResponse{}
	mi := &file_shared_proto_ward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WardResponse) ProtoMessage() {}

func (x *WardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_ward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WardResponse.ProtoReflect.Descriptor instead.
func (*WardResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_ward_proto_rawDescGZIP(), []int{1}
}

func (x *WardResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WardResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WardResponse) GetProvinceId() int32 {
	if x != nil {
		return x.ProvinceId
	}
	return 0
}

var File_shared_proto_ward_proto protoreflect.FileDescriptor

const file_shared_proto_ward_proto_rawDesc = "" +
	"\n" +
	"\x17shared/proto/ward.proto\x12\x04ward\"$\n" +
	"\x12GetWardByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"g\n" +
	"\fWardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1f\n" +
	"\vprovince_id\x18\x04 \x01(\x05R\n" +
	"provinceId2M\n" +
	"\vWardService\x12>\n" +
	"\x0eGetWardByIdHdl\x12\x18.ward.GetWardByIdRequest\x1a\x12.ward.WardResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_shared_proto_ward_proto_rawDescOnce sync.Once
	file_shared_proto_ward_proto_rawDescData []byte
)

func file_shared_proto_ward_proto_rawDescGZIP() []byte {
	file_shared_proto_ward_proto_rawDescOnce.Do(func() {
		file_shared_proto_ward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_ward_proto_rawDesc), len(file_shared_proto_ward_proto_rawDesc)))
	})
	return file_shared_proto_ward_proto_rawDescData
}

var file_shared_proto_ward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_ward_proto_goTypes = []any{
	(*GetWardByIdRequest)(nil), // 0: ward.GetWardByIdRequest
	(*WardResponse)(nil),       // 1: ward.WardResponse
}
var file_shared_proto_ward_proto_depIdxs = []int32{
	0, // 0: ward.WardService.GetWardByIdHdl:input_type -> ward.GetWardByIdRequest
	1, // 1: ward.WardService.GetWardByIdHdl:output_type -> ward.WardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_ward_proto_init() }
func file_shared_proto_ward_proto_init() {
	if File_shared_proto_ward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_ward_proto_rawDesc), len(file_shared_proto_ward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_ward_proto_goTypes,
		DependencyIndexes: file_shared_proto_ward_proto_depIdxs,
		MessageInfos:      file_shared_proto_ward_proto_msgTypes,
	}.Build()
	File_shared_proto_ward_proto = out.File
	file_shared_proto_ward_proto_goTypes = nil
	file_shared_proto_ward_proto_depIdxs = nil
}
